"""Pure rendering of the digest into HTML + plain-text. No I/O.

Email clients are unreliable with <style> blocks, so styles are inlined.
"""

# Builtin imports
from datetime import datetime
from html import escape

# Local imports
from ..models import Item

_CONTAINER = (
    "max-width:640px;margin:0 auto;padding:24px;"
    "font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;"
    "color:#1a1a1a;line-height:1.5;"
)
_H1 = "margin:0 0 4px;font-size:22px;"
_DATE = "margin:0 0 24px;color:#666;font-size:14px;"
_H2 = (
    "margin:28px 0 12px;font-size:13px;letter-spacing:.08em;text-transform:"
    "uppercase;color:#3b5bdb;border-bottom:1px solid #e5e7eb;padding-bottom:6px;"
)
_TITLE = "font-size:16px;font-weight:600;color:#1a1a1a;text-decoration:none;"
_META = "margin:2px 0 6px;color:#888;font-size:12px;"
_SUMMARY = "margin:0 0 6px;font-size:14px;"
_WHY = "margin:0;font-size:14px;color:#444;"
_FOOTER = "margin-top:28px;color:#aaa;font-size:12px;"


def _category_title(category: str) -> str:
    return category.upper() if len(category) <= 3 else category.capitalize()


def render_subject(now: datetime) -> str:
    return f"News digest — {now:%b %d, %Y}"


def _render_item_html(item: Item) -> str:
    meta = escape(item.source)
    if item.points is not None:
        meta += f" · {item.points} points"
    summary = (
        f'<p style="{_SUMMARY}">{escape(item.summary)}</p>' if item.summary else ""
    )
    why = (
        f'<p style="{_WHY}"><strong>Why it matters:</strong> {escape(item.why)}</p>'
        if item.why
        else ""
    )
    return (
        '<div style="margin:0 0 18px;">'
        f'<a href="{escape(item.url, quote=True)}" style="{_TITLE}">'
        f"{escape(item.title)}</a>"
        f'<div style="{_META}">{meta}</div>'
        f"{summary}{why}"
        "</div>"
    )


def render_html(ranked: dict[str, list[Item]], now: datetime) -> str:
    sections = []
    for category, items in ranked.items():
        if not items:
            continue
        rows = "".join(_render_item_html(item) for item in items)
        sections.append(
            f'<h2 style="{_H2}">{escape(_category_title(category))}</h2>{rows}'
        )
    body = "".join(sections) or "<p>No stories today.</p>"
    return (
        '<!doctype html><html><body style="margin:0;background:#f6f7f9;">'
        f'<div style="{_CONTAINER}">'
        f'<h1 style="{_H1}">News Digest</h1>'
        f'<p style="{_DATE}">{now:%A, %B %d, %Y}</p>'
        f"{body}"
        f'<p style="{_FOOTER}">Generated by news-agent</p>'
        "</div></body></html>"
    )


def render_text(ranked: dict[str, list[Item]], now: datetime) -> str:
    lines = [f"News Digest — {now:%A, %B %d, %Y}", ""]
    for category, items in ranked.items():
        if not items:
            continue
        heading = _category_title(category).upper()
        lines.append(heading)
        lines.append("=" * len(heading))
        for index, item in enumerate(items, 1):
            lines.append(f"{index}. {item.title}")
            lines.append(f"   {item.url}")
            if item.summary:
                lines.append(f"   {item.summary}")
            if item.why:
                lines.append(f"   Why it matters: {item.why}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"
